default: &default
  adapter: postgresql
  host: localhost
  username: user
  pool: 15

development:
  <<: *default
  database: app-dev

test:
  <<: *default
  database: app-test

production:
  <<: *default
  database: app-prod
